"""Abstract base class and exceptions for TTS providers."""

from abc import ABC, abstractmethod
from typing import AsyncGenerator


class TTSProviderError(RuntimeError):
    """Raised when a TTS provider fails to synthesize audio."""


class BaseTTSProvider(ABC):
    """
    Abstract Base Class for all Text-to-Speech (TTS) providers.

    Provides a unified interface for TTS synthesis, whether hosted locally
    (e.g., Kokoro-ONNX) or remotely (e.g., OpenRouter Fish Audio).
    """

    @property
    @abstractmethod
    def name(self) -> str:
        """Identifier of the TTS provider (e.g., 'openrouter', 'kokoro')."""

    @property
    @abstractmethod
    def is_configured(self) -> bool:
        """Return True if the provider has required credentials and models available."""

    @abstractmethod
    async def synthesize(
        self,
        text: str,
        voice: str | None = None,
        response_format: str | None = None,
    ) -> bytes:
        """
        Synthesize text into audio bytes asynchronously.

        Args:
            text: Speakable text input.
            voice: Optional voice identifier.
            response_format: Audio container/codec format (e.g., 'mp3', 'wav', 'pcm').

        Returns:
            Raw audio byte payload.
        """

    @abstractmethod
    async def stream_synthesize(
        self,
        text: str,
        voice: str | None = None,
        response_format: str | None = None,
    ) -> AsyncGenerator[bytes, None]:
        """
        Stream audio bytes as they are generated by the provider.

        Args:
            text: Speakable text input.
            voice: Optional voice identifier.
            response_format: Audio container/codec format.

        Yields:
            Audio bytes chunks.
        """
