[mypy]
ignore_missing_imports = True
plugins = pydantic.mypy

[mypy-fastapi.*]
ignore_missing_imports = True

[mypy-chromadb.*]
ignore_missing_imports = True

[mypy-faster_whisper.*]
ignore_missing_imports = True

[mypy-ctranslate2.*]
ignore_missing_imports = True

[mypy-soundfile.*]
ignore_missing_imports = True

[mypy-kokoro_onnx.*]
ignore_missing_imports = True
